// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHFXfSvxbz9sXaX1U3-jMfiLFmPuhnZgg',
    appId: '1:388297742218:web:a71c5e5b60c981f3c29a73',
    messagingSenderId: '388297742218',
    projectId: 'authtutorial-559e1',
    authDomain: 'authtutorial-559e1.firebaseapp.com',
    storageBucket: 'authtutorial-559e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFhJfDRWb_0aQCpYxT6CM5PvD3RV1Lgqc',
    appId: '1:388297742218:android:8ccf719e33a2c0ccc29a73',
    messagingSenderId: '388297742218',
    projectId: 'authtutorial-559e1',
    storageBucket: 'authtutorial-559e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhw83gVxATkabEUI77NZkHYuR028g3yfk',
    appId: '1:388297742218:ios:c67914e8749a0c53c29a73',
    messagingSenderId: '388297742218',
    projectId: 'authtutorial-559e1',
    storageBucket: 'authtutorial-559e1.appspot.com',
    iosClientId: '388297742218-3titu0t0oje1j6nfu604p48329t919md.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhw83gVxATkabEUI77NZkHYuR028g3yfk',
    appId: '1:388297742218:ios:c67914e8749a0c53c29a73',
    messagingSenderId: '388297742218',
    projectId: 'authtutorial-559e1',
    storageBucket: 'authtutorial-559e1.appspot.com',
    iosClientId: '388297742218-3titu0t0oje1j6nfu604p48329t919md.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );
}
